site_name: Tantale’s Blog
site_url: https://tantale.github.io/
nav:
  - Function parameters deprecation:
      - Requirements: articles/requirements.md
      - Deprecated Parameters Decorator: articles/deprecated_params.md
  - About: about.md
theme: mkdocs
