site_name: Tantale’s Blog
site_url: https://tantale.github.io/
nav:
  - Function parameters deprecation:
    - Requirements: en/articles/requirements.md
    - Deprecated Parameters Decorator: en/articles/deprecated_params.md
  - About: about.md
theme:
  name: material
  language: en
  logo: images/Tantale-logo.png
  favicon: images/favicon.ico
#  palette:
#    primary: red
#    accent: yellow
